#define GDCLASS(m_class, m_inherits)

#define REGISTER_CLASS_GEN_CODE(CLASS_NAME) REGISTER_CLASS_GEN_CODE_CLASS_ ## CLASS_NAME

#define EXPORT_METHOD(METHOD_NAME, ...)

#define EXPORT_CLASS(CLASS_NAME, CLASS_NAME_INHERITED) GDCLASS(CLASS_NAME, CLASS_NAME_INHERITED)			\
static void _register_methods() {			\
	REGISTER_CLASS_GEN_CODE(CLASS_NAME)			\
}			

